apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  # The pre-delete-finalizer hook is necessary because of how longhorn deploys
  # jobs on hooks.
  - pre-delete-finalizer.argocd.argoproj.io
  - pre-delete-finalizer.argocd.argoproj.io/cleanup
spec:
  destination:
    namespace: longhorn-system
    server: {{ .Values.spec.destination.server }}
  project: production
  source:
    path: longhorn
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
