apiVersion: v2
name: grafana
description: A helm chart for grafana
type: application
version: '0.1.0'
dependencies:
- name: grafana
  version: 10.5.5
  repository: https://grafana.github.io/helm-charts
