images:
  - name: quay.io/thanos/thanos
    newTag: v0.41.0@sha256:cf3e9b292e4302ad4a4955b56379703aea39516607d382a57604a3d003c35d10
resources:
- ./manifests/sealedsecret.thanos-storage.yaml
- ./manifests/deployment.thanos-query.yaml
- ./manifests/statefulset.thanos-compact.yaml
- ./manifests/statefulset.thanos-store.yaml
- ./manifests/service.thanos-query.yaml
- ./manifests/service.thanos-sidecar.yaml
- ./manifests/service.thanos-store.yaml
- ./manifests/servicemonitor.thanos-store.yaml
